# Generated by Django 5.0.1 on 2024-02-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryandy', '0003_alter_inventoryandy_remaining_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryandy',
            name='barcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
